spring:
  application:
    name: ${encounter.server.name}
  datasource:
    #driverClassName: com.mysql.cj.jdbc.Driver
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
server: 
  port: ${encounter.server.port}
  
eurika-name:
  ccip:
    patient: ${eurika-name.ccip.patient}
  
eureka:
  client:
    service-url: 
      defaultZone: ${eureka.client.serviceUrl.defaultZone}

mybatis:
  mapperLocations: classpath:mapping/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
